.TH MINIMDNSD 1 "June 2024" "version 0.1" "User Manuals"
.SH "NAME"
minimdns \- Minimal MDNS server
.SH "SYNOPSIS"
.B minimdnsd [-h host_alias_override] [-4] [-r]
.SH "DESCRIPTION"
.B minimdnsd is a minimal MDNS server, able to reply to other computers on the network at (your hostname).local
.SH "OPTIONS"
Usually this is intended to be used without any -h flag.
.IP -h
Specify a hostname override instead of using /etc/hostname - you can launch multiple instances, to get multiple overrides.
.IP -r
Create a dummy responder, it listens on 127.0.0.67:53 and forwards requests to 224.0.0.251:5353, but note: may or may not forward AAAA requests.
.IP -4
Disable IPv6 operation.
.SH "AUTHOR"
cnlohr <lohr85@gmail.com>

.SH COPYRIGHT
Copyright \(co 2024 cnlohr
.br
.SH LICENSE
minimdns is licensed under the MIT-x11 license.

