name: Build Test

on:
  push:
  pull_request:

jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential
    - name: Build
      run: make clean test deb
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-file
        path: |
          minimdnsd_*.deb
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          minimdnsd_*.deb
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
