name: Relase

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /
jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential
    - name: Build
      run: make clean test deb
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          minimdnsd_*.deb
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
